#!/usr/bin/env zsh

echo "updating system rubygems"
  cd ~/
  sudo gem update --system
  sudo gem clean

echo "Updating ruby"
  cd ~/development
  ruby_latest_version="$(curl -sSL http://ruby.thoughtbot.com/latest)"
  ruby_current_version="$(cat .ruby-version)"
  if [[ $ruby_latest_version = $ruby_current_version ]]; then
    echo "Latest ruby installed - Updating rubygems"
    gem update --system
    gem update bundler
    gem clean
  else
    ruby-install "ruby $ruby_latest_version"
    echo "$ruby_latest_version" > .ruby-version
    cd ~/development
    gem update --system
    gem install bundler --no-document
    gem clean
  fi
  cd ~/

echo "updating zsh completions"
  wget https://raw.githubusercontent.com/docker/docker/master/contrib/completion/zsh/_docker -O ~/.zsh/completions/_docker
  wget https://raw.githubusercontent.com/docker/machine/master/contrib/completion/zsh/_docker-machine -O ~/.zsh/completions/_docker-machine
  wget https://raw.githubusercontent.com/docker/compose/master/contrib/completion/zsh/_docker-compose -O ~/.zsh/completions/_docker-compose

echo "homebrew outdated"
  cd ~/
  wget https://raw.githubusercontent.com/damonmorgan/environment/master/Brewfile -O ~/Brewfile
  brew bundle
  brew update
  brew cleanup
  brew outdated

echo "npm outdated"
  npm -g outdated
